---
allowed_hosts:
- localhost
- example.com
- api.example.com
app_config:
  debug_mode: false
  environment: production
  name: My Web App
  version: 1.0.0
database:
  host: localhost
  name: my_web_app_db
  password: securepassword
  port: 5432
  username: db_user
features:
  api: true
  authentication: true
  web_sockets: false
logging:
  file_path: "/var/log/my_web_app.log"
  level: info
  log_to_file: true
server:
  host: 0.0.0.0
  port: 8080
